name: 'Swatinem/rust-cache'
description: 'Swatinem/rust-cache with better defaults'
runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab  # v2.7.5
      timeout-minutes: 2
      continue-on-error: true
