name: 'checkout, setup-python, and setup-uv'
description: 'Common steps for most Python actions.'
inputs:
  python-version:
    description: "actions/setup-python: python-version"
  python-version-file:
    description: "actions/setup-python: python-version-file"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      with:
        persist-credentials: false
    - uses: actions/setup-python@19dfb7b659fa9e60c2f89c33335ab5f6f1792b6e
      with:
        python-version: ${{ inputs.python-version }}
        python-version-file: ${{ inputs.python-version-file }}
    - uses: astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086
      with:
        version: "0.4.20"
        enable-cache: true