name: 'actions/checkout'
description: 'actions/checkout with better defaults'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      with:
        persist-credentials: false