# A simple wrapper around re-actors/alls-green so that we only need to pin in one place.
#
# Usage:
#
# check:
#   if: always()
#   needs:
#   - test
#   - build
#   uses: mhils/workflows/.github/workflows/alls-green.yml@main
#   with:
#     jobs: ${{ toJSON(needs) }}

on:
  workflow_call:
    inputs:
      jobs:
        type: string
        description: The jobs that need to pass.
        required: true

jobs:
  check:
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe  # v1.2.2
      with:
        jobs: ${{ inputs.jobs }}
