# A simple wrapper around re-actors/alls-green so that we only need to pin in one place.
#
# Usage:
#
# check:
#   if: always()
#   needs:
#   - test
#   - build
#   uses: mhils/workflows/.github/workflows/alls-green.yml@main
#   with:
#     jobs: ${{ toJSON(needs) }}

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      jobs:
        type: string
        description: >-
          A list of jobs from the `needs` context, serialized as a JSON
          string via `toJSON(needs)`
        required: true
      allowed-failures:
        type: string
        default: >-
          []
        description: >-
          Job names that are allowed to fail and not affect the outcome,
          as a comma-separated list or serialized as a JSON string
        required: false
      allowed-skips:
        type: string
        default: >-
          []
        description: >-
          Job names that are allowed to be skipped and not affect the
          outcome, as a comma-separated list or serialized as a JSON string
        required: false

jobs:
  check:
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe  # v1.2.2
      with:
        jobs: ${{ inputs.jobs }}
        allowed-failures: ${{ inputs.allowed-failures }}
        allowed-skips: ${{ inputs.allowed-skips }}
