# Usage:
#
# build:
#   uses: mhils/workflows/.github/workflows/python-build.yml@main
#   with:
#     python-version: "3.11"

on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
      python-version-file:
        type: string
      build-args:
        type: string
      artifact:
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version || (inputs.python-version-file == '' && hashFiles('.github/python-version.txt') == '' && hashFiles('.python-version') == '' && '3.11') }}
          python-version-file: ${{ inputs.python-version-file || (hashFiles('.github/python-version.txt') != '' && '.github/python-version.txt') }}
      
      # potentially add https://youtu.be/n39uvwdW5ek?t=579 here.
      
      # install all build dependencies
      - name: Install build from PyPI
        uses: install-pinned/build@208d106ca8131005eb0cda9ef437182f79db0dac  # 0.10.0
      - name: Install setuptools from PyPI
        uses: install-pinned/setuptools@0d74f5e9d09987231503f9b1c8e6c918e1c45fb8  # 65.6.3
      - name: Install wheel from PyPI
        uses: install-pinned/wheel@53c86096b91671b8bb138a78a963c1e88295a5a3  # 0.38.4
        
      # build wheel without network connection where possible
      - if: runner.os == 'Linux'
        run: sudo unshare --net -- $(which python3) -m build --no-isolation ${{ inputs.build-args }}
      - if: runner.os != 'Linux'
        run: python3 -m build --no-isolation ${{ inputs.build-args }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact || 'wheels' }}
          path: dist/
