# Usage:
#
# build:
#   uses: mhils/workflows/.github/workflows/python-build.yml@main
#   with:
#     python-version: "3.11"

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
      python-version-file:
        type: string
      build-args:
        type: string
      artifact:
        type: string
      build-backend:
        type: string
        default: 'setuptools'
      build-offline:
        type: boolean
        default: true

jobs:
  build:
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version || (inputs.python-version-file == '' && hashFiles('.github/python-version.txt') == '' && hashFiles('.python-version') == '' && '3.11') || '' }}
          python-version-file: ${{ inputs.python-version-file || (inputs.python-version == '' && hashFiles('.github/python-version.txt') != '' && '.github/python-version.txt') || '' }}
      
      - uses: ./.github/actions/pre-build
        if: ${{ hashFiles('.github/actions/pre-build/action.yml') != '' }}
      
      # install all build dependencies
      - name: Install build from PyPI
        uses: install-pinned/build@11bbf2deeb1a44228c45910f3b57e346927960b4  # 0.10.0
      - name: Install wheel from PyPI
        uses: install-pinned/wheel@bef0f25d353f388434010690edbc75ec156e6031  # 0.38.4

      - name: Install setuptools from PyPI
        if: inputs.build-backend == 'setuptools'
        uses: install-pinned/setuptools@faab8e3664bc14679352c4c87a27e298d8c8ce5c  # 67.3.2
      - name: Install pdm-backend from PyPI
        if: inputs.build-backend == 'pdm-backend'
        uses: install-pinned/pdm-backend@74732366c54354b809a255179cb5626c1d9be436  # 2.1.7

      # build wheel without network connection where possible
      - if: (runner.os == 'Linux' && inputs.build-offline)
        run: sudo unshare --net -- $(which python3) -m build --no-isolation ${{ inputs.build-args }}
      - if: (runner.os == 'Linux' && inputs.build-offline) == false
        run: python3 -m build --no-isolation ${{ inputs.build-args }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact || 'wheels' }}
          path: dist/
