# Usage:
#
# test:
#   strategy:
#     matrix:
#       include:
#         - os: windows-latest
#           py: "3.11"
#         - os: macos-latest
#           py: "3.11"
#         - os: ubuntu-latest
#           py: "3.11"
#         - os: ubuntu-latest
#           py: "3.10"
#         - os: ubuntu-latest
#           py: "3.9"
#   uses: mhils/workflows/.github/workflows/python-tox.yml@main
#   with:
#     cmd: tox -e py -- -v
#     os: ${{ matrix.os }}
#     python-version: ${{ matrix.py }}

on:
  workflow_call:
    inputs:
      cmd:
        type: string
        required: true
      os:
        type: string
      python-version:
        type: string
      python-version-file:
        type: string

jobs:
  tox:
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version || (inputs.python-version-file == '' && hashFiles('.github/python-version.txt') == '' && hashFiles('.python-version') == '' && '3.11') || '' }}
          python-version-file: ${{ inputs.python-version-file || (hashFiles('.github/python-version.txt') != '' && '.github/python-version.txt') || '' }}

      - name: Install tox from PyPI
        uses: install-pinned/tox@860f16fa13d5806c16252fde07a79d6f2a7b9f8f  # 4.2.8
        
      - run: ${{ inputs.cmd }}
