# Usage:
#
# test:
#   strategy:
#     matrix:
#       include:
#         - os: windows-latest
#           py: "3.11"
#         - os: macos-latest
#           py: "3.11"
#         - os: ubuntu-latest
#           py: "3.11"
#         - os: ubuntu-latest
#           py: "3.10"
#         - os: ubuntu-latest
#           py: "3.9"
#   uses: mhils/workflows/.github/workflows/python-uv.yml@main
#   with:
#     cmd: uv run tox -e py -- -v
#     os: ${{ matrix.os }}
#     python-version: ${{ matrix.py }}

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      cmd:
        type: string
        required: true
      os:
        type: string
      python-version:
        type: string
      python-version-file:
        type: string

jobs:
  tox:
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          persist-credentials: false
      - uses: actions/setup-python@19dfb7b659fa9e60c2f89c33335ab5f6f1792b6e
        with:
          python-version: ${{ inputs.python-version || (inputs.python-version-file == '' && hashFiles('.github/python-version.txt') == '' && hashFiles('.python-version') == '' && '3.13') || '' }}
          python-version-file: ${{ inputs.python-version-file || (inputs.python-version == '' && hashFiles('.github/python-version.txt') != '' && '.github/python-version.txt') || '' }}
      - uses: astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086
        with:
          version: "0.4.20"
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - run: ${{ inputs.cmd }}
